In [14]:
import investpy as inv
import yfinance as yf
from datetime import datetime, date, timedelta
from dateutil.relativedelta import relativedelta
import pandas as pd
n_backtesting_years = 1
br = inv.stocks.get_stocks(country='brazil')
carteira=[]
blacklist= ['VSPT3']#['AHEB3','AIGB34','ANCR11B','ARNC34','BALM3','BALM4','BAUH4','BBYY34','BDLL4','BGIP3','BIIB34','BMEB3','BMIN3',
#'BMIN4','BMYB34','BNBR3','BRGE12','BRGE6','BRIV3','BRSR5','BSLI4','CBEE3','CEDO3','CEEB5','CEED3','CGAS3','COCE3','COTY34',
#'CRDE3','CRIV3','CRIV4','CRPG6','CSRN3','CTKA4','CTNM3','CTSH34','DDNB34','DEAI34','DRIT11B','DTCY3','DUKB34','EALT3','ECPR3',
#'EDFO11B','EKTR4','ENMT3','ENMT4','ESTR4','FESA3','FMXB34','FRIO3','FTCE11B','GDBR34','GEPA3','GPAR3','GPSI34','GSHP3','HALI34',
#'HBTS5','HSHY34','JOPA3','JOPA4','KMBB34','LATR11B','LIPR3','LUXM4','MAPT3','MERC4','METB34','MOAR3','MRSA3B','MSPA3','NUTR3',
#'PATI3','PATI4','PEAB3','PEAB4','PLAS3','PRSN11B','ROST34','RPAD3','RPAD5','RPAD6','SAIC11B','SLED3','SOND5','SOND6','TCNO3',
#'TCNO4','TEKA4','TRVC34','TXRX4','UBSG34','UNIP5','UPAC34','USIM6','WLMM3','WTSP11B','WUNI34','XRXB34']

for a in br['symbol']:
    if ((a[(-2):] != '11')&(a not in blacklist)):
        carteira.append(a+'.SA')
        
dt=yf.download(carteira,  start=(date.today() - relativedelta(years=n_backtesting_years)),end=date.today(), interval='1d')
#dt=yf.download(carteira,start='2022-01-13',end='2023-01-13')
dt.sort_index(inplace=True)
dt=dt.reset_index().sort_values("Date").dropna(axis=1, how='all')
#dt=pd.read_excel('offline_database.xlsx')

dt['Date'] = pd.to_datetime(dt['Date'],utc=True).dt.date
dt.set_index('Date',inplace=True)
dt = dt.groupby(dt.index).sum()
print(dt)

df3=dt.reset_index().sort_values("Date").dropna(axis=1, how='all').set_index("Date").sort_index().copy()
#df2 = df3.drop(columns=[col for col in df3.columns if (df3[col].isnull().sum()==0)],axis=1).sort_index()
print(df3.isnull().sum().sort_values())

[*********************100%%**********************]  557 of 557 completed

117 Failed downloads:
['CARD3.SA', 'IDVL3.SA', 'CESP5.SA', 'CELP3.SA', 'CAMB4.SA', 'BRHT11B.SA', 'JBDU4.SA', 'LIQO3.SA', 'IDVL4.SA', 'DMMO3.SA', 'TASA15.SA', 'ELDO11B.SA', 'CCXC3.SA', 'LAME3.SA', 'CNTO3.SA', 'CELP6.SA', 'PNVL4.SA', 'JBDU3.SA', 'TIET4.SA', 'GNDI3.SA', 'TIMP3.SA', 'LBRN34.SA', 'CPRE3.SA', 'UTEC34.SA', 'BRDT3.SA', 'CRDE3.SA', 'LOGN12.SA', 'FBOK34.SA', 'VVAR3.SA', 'MEND5.SA', 'TIFF34.SA', 'TIET2.SA', 'IDNT3.SA', 'PCAR4.SA', 'IGTA3.SA', 'BIDI3.SA', 'RLOG3.SA', 'BIDI4.SA', 'CLGN34.SA', 'MMXM3.SA', 'CELP5.SA', 'JBDU2.SA', 'CESP6.SA', 'TIET3.SA', 'ENMA3B.SA', 'SULA4.SA', 'TASA17.SA', 'HGTX3.SA', 'CELP7.SA', 'TRPN3.SA', 'SPRN34.SA', 'GFSA1.SA', 'JBDU1.SA', 'ATSA11B.SA', 'ENBR3.SA', 'BBRK3.SA', 'BTOW3.SA', 'MEND6.SA', 'TESA3.SA', 'ELPL3.SA', 'ELEK4.SA', 'GBIO33.SA', 'TWTR34.SA', 'JPSA3.SA', 'IDVL9.SA', 'EEEL3.SA', 'CESP3.SA', 'MTIG4.SA', 'ITEC3.SA', 'CAMB10.SA', 'SMLS3.SA', 'TOYB4.SA', 'ELEK3.SA', 'SPRI3.SA', 'SEDU3.SA', 'JCPC34.SA', 'GPCP3.SA', 'DMMO3T.SA', 'OMGE3.SA', 'EEEL4.SA', 'BTTL3.SA', 'CHKE34.SA', 'SULA3.SA', 'AVON34.SA', 'LINX3.SA', 'WPLZ11B.SA', 'RANI4.SA', 'POMO10.SA', 'CCPR3.SA', 'BIDI4T.SA', 'LLIS3.SA', 'BMLC11B.SA', 'LAME4.SA', 'TCNO3.SA', 'WIZS3.SA', 'WSON33.SA', 'BKBR3.SA', 'NATU3.SA', 'PARD3.SA', 'LCAM3.SA', 'CEPE5.SA', 'TOYB3.SA', 'TASA13.SA', 'BRML3.SA', 'MYPK12.SA', 'SMLS3T.SA', 'TCNO4.SA', 'NVIF11B.SA', 'BSEV3.SA', 'VIVT4.SA', 'DTEX3.SA']: Exception('%ticker%: No timezone found, symbol may be delisted')
['ANIM3T.SA', 'CVCB3T.SA', 'SEER3T.SA', 'SANC34.SA', 'CPRE3T.SA']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2022-11-02 -> 2023-11-02)')
['TORM13.SA']: Exception("%ticker%: Period 'max' is invalid, must be one of ['1d', '5d']")

            Adj Close                                                         \
            AALL34.SA   AALR3.SA  AAPL34.SA  ABBV34.SA  ABCB10.SA   ABCB4.SA
Date
2022-11-03  70.589996  21.219999  35.388012  44.916992   0.000000  20.169052
2022-11-04  70.820000  20.990000  34.876160  44.480549   0.000000  20.450348
2022-11-07  73.779999  20.930000  35.847012  46.511589   0.000000  19.737728
2022-11-08  73.400002  21.209999  35.727528  47.051662   0.000000  20.159676
2022-11-09  72.680000  21.240000  34.846287  47.078480   0.000000  19.775234
...               ...        ...        ...        ...        ...        ...
2023-10-26  55.680000   9.730000  41.599998  45.500000  19.010000  19.270000
2023-10-27  54.900002   9.490000  42.080002  43.400002  18.980000  18.990000
2023-10-30  56.400002   9.370000  42.849998  44.630001  18.889999  18.740000
2023-10-31  55.950001   9.750000  42.930000  44.040001  19.889999  18.709999
2023-11-01  55.250000   9.440000  43.240002  44.720001  18.610001  19.000000

                                                        ...    Volume  \
             ABEV3.SA  ABTT34.SA    ACNB34.SA ADHM3.SA  ... WFCO34.SA
Date                                                    ...
2022-11-03  15.218159  40.179005  1303.664917     1.56  ...      1969
2022-11-04  15.626637  39.871288  1284.997192     1.56  ...     16110
2022-11-07  15.541142  41.724098  1373.209351     1.56  ...      1696
2022-11-08  15.902121  41.724098  1373.209351     1.56  ...      3877
2022-11-09  15.655134  41.724098  1362.176758     1.56  ...      3081
...               ...        ...          ...      ...  ...       ...
2023-10-26  12.630000  39.169998  1458.400024     1.56  ...       736
2023-10-27  12.290000  38.709999  1448.670044     1.56  ...       696
2023-10-30  12.360000  39.099998  1479.040039     1.56  ...      1789
2023-10-31  12.860000  39.419998  1479.040039     1.56  ...      3697
2023-11-01  12.990000  39.590000  1498.050049     1.56  ...      1612

                                                                               \
           WHRL3.SA WHRL4.SA WLMM3.SA WLMM4.SA WTSP11B.SA WUNI34.SA XPHT12.SA
Date
2022-11-03     5600     6200      0.0   2900.0        0.0        87       1.0
2022-11-04     4700     6000      0.0    700.0        0.0        27     760.0
2022-11-07     3300     5100      0.0   1200.0        1.0         5      43.0
2022-11-08     2300     3600      0.0   1200.0        0.0         0      68.0
2022-11-09      600     4100      0.0   1300.0        2.0         0     792.0
...             ...      ...      ...      ...        ...       ...       ...
2023-10-26        0     8600      0.0   1500.0        0.0         0       0.0
2023-10-27     1000     9000      0.0   1200.0        0.0        81       0.0
2023-10-30      800    11600      0.0   5100.0        0.0        42       0.0
2023-10-31    11600    11200      0.0   1600.0        0.0       300       0.0
2023-11-01      200    22000      0.0   1900.0        0.0       151       0.0


           XRXB34.SA YDUQ3.SA
Date
2022-11-03      16.0  6481800
2022-11-04       7.0  5335600
2022-11-07      11.0  8476400
2022-11-08       5.0  6679800
2022-11-09       0.0  5333200
...              ...      ...
2023-10-26       0.0  3632900
2023-10-27      30.0  4291500
2023-10-30       9.0  4088500
2023-10-31       0.0  2897000
2023-11-01       0.0  4690900

[250 rows x 2640 columns]
Adj Close  AALL34.SA    0
Low        WUNI34.SA    0
           XPHT12.SA    0
           XRXB34.SA    0
           YDUQ3.SA     0
                       ..
High       AALR3.SA     0
           AAPL34.SA    0
           ABBV34.SA    0
           ABCB4.SA     0
Volume     YDUQ3.SA     0
Length: 2640, dtype: int64

In [17]:
df3["Adj Close"].reset_index()

,Date,AALL34.SA,AALR3.SA,AAPL34.SA,ABBV34.SA,ABCB10.SA,ABCB4.SA,ABEV3.SA,ABTT34.SA,ACNB34.SA,...,WFCO34.SA,WHRL3.SA,WHRL4.SA,WLMM3.SA,WLMM4.SA,WTSP11B.SA,WUNI34.SA,XPHT12.SA,XRXB34.SA,YDUQ3.SA
0,2022-11-03,70.589996,21.219999,35.388012,44.916992,0.000000,20.169052,15.218159,40.179005,1303.664917,...,57.737724,4.873061,5.347125,21.710955,23.925348,40.652458,59.176125,36.331635,67.473335,15.873201
1,2022-11-04,70.820000,20.990000,34.876160,44.480549,0.000000,20.450348,15.626637,39.871288,1284.997192,...,57.826443,4.988856,5.385663,21.710955,23.954298,40.652458,59.574337,33.389565,68.595390,16.149773
2,2022-11-07,73.779999,20.930000,35.847012,46.511589,0.000000,19.737728,15.541142,41.724098,1373.209351,...,59.945892,5.008156,5.241146,21.710955,23.906042,40.652458,61.972870,34.060909,70.661858,14.431081
3,2022-11-08,73.400002,21.209999,35.727528,47.051662,0.000000,20.159676,15.902121,41.724098,1373.209351,...,59.748734,4.940608,5.327856,21.710955,24.031509,40.652458,61.972870,33.429054,71.363144,13.808796
4,2022-11-09,72.680000,21.240000,34.846287,47.078480,0.000000,19.775234,15.655134,41.724098,1362.176758,...,58.792519,4.979207,5.270049,21.710955,25.044886,40.652458,61.972870,33.389565,71.363144,13.551981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,2023-10-26,55.680000,9.730000,41.599998,45.500000,19.010000,19.270000,12.630000,39.169998,1458.400024,...,49.430000,4.230000,4.230000,28.040001,36.630001,36.000000,66.660004,0.000000,78.589996,18.780001
246,2023-10-27,54.900002,9.490000,42.080002,43.400002,18.980000,18.990000,12.290000,38.709999,1448.670044,...,48.490002,4.270000,4.210000,28.040001,37.299999,36.000000,57.500000,0.000000,61.080002,18.400000
247,2023-10-30,56.400002,9.370000,42.849998,44.630001,18.889999,18.740000,12.360000,39.099998,1479.040039,...,49.650002,4.230000,4.120000,28.040001,36.900002,36.000000,55.849998,0.000000,61.150002,17.719999
248,2023-10-31,55.950001,9.750000,42.930000,44.040001,19.889999,18.709999,12.860000,39.419998,1479.040039,...,49.790001,4.180000,4.100000,28.040001,37.400002,36.000000,57.000000,0.000000,61.150002,17.730000
249,2023-11-01,55.250000,9.440000,43.240002,44.720001,18.610001,19.000000,12.990000,39.590000,1498.050049,...,49.320000,4.200000,4.100000,28.040001,37.099998,36.000000,56.759998,0.000000,61.150002,18.040001

In [22]:
df3.columns
df3['Volume']

,AALL34.SA,AALR3.SA,AAPL34.SA,ABBV34.SA,ABCB10.SA,ABCB4.SA,ABEV3.SA,ABTT34.SA,ACNB34.SA,ADHM3.SA,...,WFCO34.SA,WHRL3.SA,WHRL4.SA,WLMM3.SA,WLMM4.SA,WTSP11B.SA,WUNI34.SA,XPHT12.SA,XRXB34.SA,YDUQ3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2022-11-03,497,231000,581856,144,0.0,1088500,26575500,27,107,0.0,...,1969,5600,6200,0.0,2900.0,0.0,87,1.0,16.0,6481800
2022-11-04,9240,327200,719738,272,0.0,1074800,30212300,9,4,0.0,...,16110,4700,6000,0.0,700.0,0.0,27,760.0,7.0,5335600
2022-11-07,6303,193100,1019194,368,0.0,1895300,32125700,6,14,0.0,...,1696,3300,5100,0.0,1200.0,1.0,5,43.0,11.0,8476400
2022-11-08,187,211800,461946,16,0.0,652700,31603000,0,0,0.0,...,3877,2300,3600,0.0,1200.0,0.0,0,68.0,5.0,6679800
2022-11-09,5748,188100,847758,38992,0.0,776800,27623800,0,1439,0.0,...,3081,600,4100,0.0,1300.0,2.0,0,792.0,0.0,5333200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-10-26,25057,42500,138466,35,4700.0,591300,25002300,1,2,0.0,...,736,0,8600,0.0,1500.0,0.0,0,0.0,0.0,3632900
2023-10-27,6357,104900,126986,226,700.0,392500,27730300,22,7,0.0,...,696,1000,9000,0.0,1200.0,0.0,81,0.0,30.0,4291500
2023-10-30,25512,111800,175824,9349,200.0,644500,26078000,1,194,0.0,...,1789,800,11600,0.0,5100.0,0.0,42,0.0,9.0,4088500
2023-10-31,665,66800,39579,96,600.0,487800,64210200,6,0,0.0,...,3697,11600,11200,0.0,1600.0,0.0,300,0.0,0.0,2897000
2023-11-01,224,36500,133957,35,4300.0,423600,40528700,4,1,0.0,...,1612,200,22000,0.0,1900.0,0.0,151,0.0,0.0,4690900

In [6]:
# end_date = date.today()
# start_date = end_date - timedelta(days=1)
# # start_time = end_date - timedelta(minutes=3)
# br = yf.download(carteira, start=start_date, end=end_date, interval='1m')
# br

NameError: name 'date' is not defined

In [ ]:
# end_date = date.today()
# start_date = end_date - timedelta(days=1)
# # start_time = end_date - timedelta(minutes=3)
# br = yf.download(carteira, start=start_date, end=end_date, interval='1m')
# br

NameError: name 'date' is not defined

In [5]:
# %pip install python-dateutil
%pip install --upgrade pip

Requirement already satisfied: pip in c:\users\delly\appdata\local\programs\python\python311\lib\site-packages (23.1.2)
Collecting pip
  Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
Successfully installed pip-23.3.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts pip.exe, pip3.11.exe and pip3.exe are installed in 'c:\Users\delly\AppData\Local\Programs\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.